spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subject
    username: subject
    password: subject
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    open-in-view: false